[package]
name = "bevy_extension"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
resolver = "2"
members = [
    "crates/bevy_jolt",
    "crates/bevy_jolt/jolt_sys",
    "crates/bevy_prefab",
]
